curl -H "Content-type:application/json" --data '{"uid": "1", "eleid": "1", "conid": "1", "parid": "1"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "2", "eleid": "1", "conid": "1", "parid": "2"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "3", "eleid": "1", "conid": "1", "parid": "3"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "4", "eleid": "1", "conid": "1", "parid": "1"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "5", "eleid": "1", "conid": "1", "parid": "2"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "6", "eleid": "1", "conid": "1", "parid": "3"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "7", "eleid": "1", "conid": "1", "parid": "1"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "8", "eleid": "1", "conid": "1", "parid": "2"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "9", "eleid": "1", "conid": "1", "parid": "3"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "10", "eleid": "1", "conid": "1", "parid": "1"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "11", "eleid": "1", "conid": "1", "parid": "2"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "12", "eleid": "1", "conid": "1", "parid": "3"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "13", "eleid": "1", "conid": "1", "parid": "1"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "14", "eleid": "1", "conid": "1", "parid": "2"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "15", "eleid": "1", "conid": "1", "parid": "3"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "16", "eleid": "1", "conid": "1", "parid": "1"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "17", "eleid": "1", "conid": "1", "parid": "2"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "18", "eleid": "1", "conid": "1", "parid": "3"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "19", "eleid": "1", "conid": "1", "parid": "1"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "20", "eleid": "1", "conid": "1", "parid": "2"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "21", "eleid": "1", "conid": "1", "parid": "3"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "22", "eleid": "1", "conid": "1", "parid": "1"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "23", "eleid": "1", "conid": "1", "parid": "2"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "24", "eleid": "1", "conid": "1", "parid": "3"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "25", "eleid": "1", "conid": "1", "parid": "1"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "26", "eleid": "1", "conid": "1", "parid": "2"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "27", "eleid": "1", "conid": "1", "parid": "3"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "28", "eleid": "1", "conid": "1", "parid": "1"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "29", "eleid": "1", "conid": "1", "parid": "2"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "30", "eleid": "1", "conid": "1", "parid": "3"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "31", "eleid": "1", "conid": "1", "parid": "1"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "32", "eleid": "1", "conid": "1", "parid": "2"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "33", "eleid": "1", "conid": "1", "parid": "3"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "34", "eleid": "1", "conid": "1", "parid": "1"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "35", "eleid": "1", "conid": "1", "parid": "2"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "36", "eleid": "1", "conid": "1", "parid": "3"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "37", "eleid": "1", "conid": "1", "parid": "1"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "38", "eleid": "1", "conid": "1", "parid": "2"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "39", "eleid": "1", "conid": "1", "parid": "3"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "40", "eleid": "1", "conid": "1", "parid": "1"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "41", "eleid": "1", "conid": "1", "parid": "2"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "42", "eleid": "1", "conid": "1", "parid": "3"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "43", "eleid": "1", "conid": "1", "parid": "1"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "44", "eleid": "1", "conid": "1", "parid": "2"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "45", "eleid": "1", "conid": "1", "parid": "3"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "46", "eleid": "1", "conid": "1", "parid": "1"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "47", "eleid": "1", "conid": "1", "parid": "2"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "48", "eleid": "1", "conid": "1", "parid": "3"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "49", "eleid": "1", "conid": "1", "parid": "1"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "50", "eleid": "1", "conid": "1", "parid": "2"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "51", "eleid": "1", "conid": "2", "parid": "3"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "52", "eleid": "1", "conid": "2", "parid": "1"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "53", "eleid": "1", "conid": "2", "parid": "2"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "54", "eleid": "1", "conid": "2", "parid": "3"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "55", "eleid": "1", "conid": "2", "parid": "1"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "56", "eleid": "1", "conid": "2", "parid": "2"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "57", "eleid": "1", "conid": "2", "parid": "3"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "58", "eleid": "1", "conid": "2", "parid": "1"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "59", "eleid": "1", "conid": "2", "parid": "2"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "60", "eleid": "1", "conid": "2", "parid": "3"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "61", "eleid": "1", "conid": "2", "parid": "1"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "62", "eleid": "1", "conid": "2", "parid": "2"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "63", "eleid": "1", "conid": "2", "parid": "3"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "64", "eleid": "1", "conid": "2", "parid": "1"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "65", "eleid": "1", "conid": "2", "parid": "2"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "66", "eleid": "1", "conid": "2", "parid": "3"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "67", "eleid": "1", "conid": "2", "parid": "1"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "68", "eleid": "1", "conid": "2", "parid": "2"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "69", "eleid": "1", "conid": "2", "parid": "3"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "70", "eleid": "1", "conid": "2", "parid": "1"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "71", "eleid": "1", "conid": "2", "parid": "2"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "72", "eleid": "1", "conid": "2", "parid": "3"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "73", "eleid": "1", "conid": "2", "parid": "1"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "74", "eleid": "1", "conid": "2", "parid": "2"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "75", "eleid": "1", "conid": "2", "parid": "3"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "76", "eleid": "1", "conid": "2", "parid": "1"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "77", "eleid": "1", "conid": "2", "parid": "2"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "78", "eleid": "1", "conid": "2", "parid": "3"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "79", "eleid": "1", "conid": "2", "parid": "1"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "80", "eleid": "1", "conid": "2", "parid": "2"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "81", "eleid": "1", "conid": "2", "parid": "3"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "82", "eleid": "1", "conid": "2", "parid": "1"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "83", "eleid": "1", "conid": "2", "parid": "2"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "84", "eleid": "1", "conid": "2", "parid": "3"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "85", "eleid": "1", "conid": "2", "parid": "1"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "86", "eleid": "1", "conid": "2", "parid": "2"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "87", "eleid": "1", "conid": "2", "parid": "3"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "88", "eleid": "1", "conid": "2", "parid": "1"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "89", "eleid": "1", "conid": "2", "parid": "2"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "90", "eleid": "1", "conid": "2", "parid": "3"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "91", "eleid": "2", "conid": "1", "parid": "1"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "92", "eleid": "2", "conid": "1", "parid": "2"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "93", "eleid": "2", "conid": "1", "parid": "3"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "94", "eleid": "2", "conid": "1", "parid": "1"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "95", "eleid": "2", "conid": "1", "parid": "2"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "96", "eleid": "2", "conid": "1", "parid": "3"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "97", "eleid": "2", "conid": "1", "parid": "1"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "98", "eleid": "2", "conid": "1", "parid": "2"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "99", "eleid": "2", "conid": "1", "parid": "3"}' http://localhost/mineBlock
curl -H "Content-type:application/json" --data '{"uid": "100", "eleid": "2", "conid": "1", "parid": "1"}' http://localhost/mineBlock